WIP: Maze Generation
Realiante/You-dug-too-deep pull request #12
Opened 2021-02-04 21:23 UTC by ukeruk

2021-02-06 09:00 UTC, Realiante requested changes
This is a mess. But a working mess, meaning you are 1/2 of the way there. Optimize and clean this up and you will have some good code.

2021-02-06 09:03 UTC, ukeruk commented on mazegen.py
> +import random
Correct. Will fix.

2021-02-06 09:04 UTC, ukeruk commented on mazegen.py
> +maze = []
Haven't cleaned up the code. They will be removed.

2021-02-06 09:04 UTC, ukeruk commented on mazegen.py
> +                print(Fore.RED + 'w', end=" ")
Good idea.

2021-02-06 09:04 UTC, ukeruk commented on mazegen.py
> +startPoint = None
Unremoved code. WIll fix.

2021-02-06 09:05 UTC, ukeruk commented on mazegen.py
> +from colorama import init
Code is copy-pasted. You're right. Will be fixed.

2021-02-06 09:05 UTC, ukeruk commented on mazegen.py
> +queueEnd = []
Correct. Code isn't finished. Will be fixed.

2021-02-06 09:07 UTC, ukeruk commented on mazegen.py
> +        break
I'm not sure I understand the solution? The reason is unfinished code and I found this better than going from right to left or vice versa. This will be changed though, you are correct about it being bad practice.

2021-02-07 13:58 UTC, Realiante requested changes
Some changes are requested before i can implement multiple path hack solution

2021-02-07 13:58 UTC, Realiante commented on maze.py
> +            y += 1
Missing a newline at the end of the file

2021-02-07 13:58 UTC, Realiante commented on mazegen.py
> +__walls = []
Functional parameters in global

2021-02-07 13:58 UTC, Realiante commented on mazegen.py
> +maze = []
This should be a return of some function

2021-02-07 13:58 UTC, Realiante commented on mazegen.py
> +            __walls.append([rand_wall[0], rand_wall[1] - 1])
Seems like this code is mostly duplicated. Probably there should be some reuse, although this is good enough...ish

2021-02-07 14:17 UTC, Realiante commented on mazegen.py
> +            __walls.append([rand_wall[0], rand_wall[1] - 1])
All the problems boil down to unnecessary focus on functional programming when much better result in this instance could be achieved with a class structure

2021-02-07 14:17 UTC, Realiante commented
All the problems boil down to unnecessary focus on functional programming when much better result in this instance could be achieved with a class structure

2021-02-07 15:26 UTC, Realiante requested changes
Starting to take shape, but laziness is palpable

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    maze = []
This code does nothing and is actively harmful!

in python `self.param` makes the `param` an attribute of the class without the need for external declaration.
declaring the attribute outside of init makes it a static.

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +        return mz_str
Shouldn't this belong to maze data class?

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +            self.delete_wall(rand_wall)
This loop is needlessly confusing. Please simplify it

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def create_start(self):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def create_end(self):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def generate_path(self):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def delete_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def left_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def right_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def bottom_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def upper_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def check_right_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def check_bottom_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def check_upper_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def check_left_wall(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +    def surrounding_cells(self, rand_wall):
method should be private

2021-02-07 15:26 UTC, Realiante commented on maze.py
> +        self.generate_path()
This init could be simplified and repeated generation of mazes can be allowed:

```suggestion
    def __init__(self, h, w):
        self.height = h
        self.width = w
        self.maze = []  # So interpreter will know maze is a list
        self.generate_maze()
        
        
    def generate_maze(self):
        self.maze = []  # Clearing the maze
        for _ in range(0, self.height):
            line = []
            for _ in range(0, self.width):
                line.append(self.__null)
            self.maze.append(line)
        starting_height = int(random.random() * self.height)
        starting_width = int(random.random() * self.width)
        if starting_height == 0:
            starting_height += 1
        if starting_height == self.height - 1:
            starting_height -= 1
        if starting_width == 0:
            starting_width += 1
        if starting_width == self.width - 1:
            starting_width -= 1
            
        self.maze[starting_height][starting_width] = self.__floor
        self.__walls.append([starting_height - 1, starting_width])
        self.__walls.append([starting_height, starting_width - 1])
        self.__walls.append([starting_height, starting_width + 1])
        self.__walls.append([starting_height + 1, starting_width])
        
        # Denote walls in maze
        self.maze[starting_height - 1][starting_width] = self.__wall
        self.maze[starting_height][starting_width - 1] = self.__wall
        self.maze[starting_height][starting_width + 1] = self.__wall
        self.maze[starting_height + 1][starting_width] = self.__wall
        self.generate_path()
```

2021-02-07 15:36 UTC, ukeruk commented on maze.py
> +    maze = []
TIL

2021-02-07 15:45 UTC, ukeruk commented on maze.py
> +        return mz_str
Why?

2021-02-07 15:51 UTC, Realiante commented on maze.py
> +        return mz_str
As this prints a maze data.
Maze builder should probably consist of its width, length and only then a __str__() of the Maze data.
I don't think to strings are necessary but whatever makes more sense to you.

2021-02-07 16:10 UTC, Realiante commented on maze.py
> +    # __key = 'key' create a use for it in the future
```suggestion
    # todo: __key = 'key' create a use for it in the future
```

2021-02-07 16:10 UTC, Realiante commented on maze.py
> +        return mz_str
It is decided to be a to string of the builder. I dont mind

2021-02-07 16:13 UTC, Realiante reviewed
All done.

2021-02-07 16:13 UTC, Realiante commented on mazegen.py
> +print(mz)
No new line at the end of file
```suggestion
print(mz)

```

2021-02-07 16:14 UTC, Realiante approved these changes

2021-02-07 16:39 UTC, merged

2021-02-07 16:41 UTC, Realiante commented
Done , merged the wip maze generation.
Fully functional and only considered WIP because it generates only a single path